

export const locations = [
  { "key": "Albany_OR", "text": "Albany, OR" },
  { "key": "Abilene_TX", "text": "Abilene, TX" },
  { "key": "Akron_OH", "text": "Akron, OH" },
  { "key": "Albany_Schenectady_Troy_NY", "text": "Albany-Schenectady-Troy, NY" },
  { "key": "Albuquerque_NM", "text": "Albuquerque, NM" },
  { "key": "Alexandria_LA", "text": "Alexandria, LA" },
  { "key": "Allentown_Bethlehem_Easton_PA-NJ", "text": "Allentown-Bethlehem-Easton, PA-NJ" },
  { "key": "Albany_GA", "text": "Albany, GA" },
  { "key": "Altoona_PA", "text": "Altoona, PA" },
  { "key": "Amarillo_TX", "text": "Amarillo, TX" },
  { "key": "Ames_IA", "text": "Ames, IA" },
  { "key": "Anchorage_AK", "text": "Anchorage, AK" },
  { "key": "Anniston_Oxford_Jacksonville_AL", "text": "Anniston-Oxford-Jacksonville, AL" },
  { "key": "Ann_Arbor_MI", "text": "Ann Arbor, MI" },
  { "key": "Appleton_WI", "text": "Appleton, WI" },
  { "key": "Asheville_NC", "text": "Asheville, NC" },
  { "key": "Atlantic_City_Hammonton_NJ", "text": "Atlantic City-Hammonton, NJ" },
  { "key": "Athens_Clarke_County_GA", "text": "Athens-Clarke County, GA" },
  { "key": "Atlanta_Sandy_Springs_Roswell_GA", "text": "Atlanta-Sandy Springs-Roswell, GA" },
  { "key": "Auburn_Opelika_AL", "text": "Auburn-Opelika, AL" },
  { "key": "Augusta_Richmond_County_GA-SC", "text": "Augusta-Richmond County, GA-SC" },
  { "key": "Austin_Round_Rock_TX", "text": "Austin-Round Rock, TX" },
  { "key": "Bakersfield_CA", "text": "Bakersfield, CA" },
  { "key": "Baltimore_Columbia_Towson_MD", "text": "Baltimore-Columbia-Towson, MD" },
  { "key": "Bangor_ME", "text": "Bangor, ME" },
  { "key": "Barnstable_Town_MA", "text": "Barnstable Town, MA" },
  { "key": "Baton_Rouge_LA", "text": "Baton Rouge, LA" },
  { "key": "Battle_Creek_MI", "text": "Battle Creek, MI" },
  { "key": "Bay_City_MI", "text": "Bay City, MI" },
  { "key": "Beaumont_Port_Arthur_TX", "text": "Beaumont-Port Arthur, TX" },
  { "key": "Beckley_WV", "text": "Beckley, WV" },
  { "key": "Bellingham_WA", "text": "Bellingham, WA" },
  { "key": "Billings_MT", "text": "Billings, MT" },
  { "key": "Binghamton_NY", "text": "Binghamton, NY" },
  { "key": "Birmingham_Hoover_AL", "text": "Birmingham-Hoover, AL" },
  { "key": "Blacksburg_Christiansburg_Radford_VA", "text": "Blacksburg-Christiansburg-Radford, VA" },
  { "key": "Boulder_CO", "text": "Boulder, CO" },
  { "key": "Bloomington_IN", "text": "Bloomington, IN" },
  { "key": "Bloomington_IL", "text": "Bloomington, IL" },
  { "key": "Bend_Redmond_OR", "text": "Bend-Redmond, OR" },
  { "key": "Boise_City_ID", "text": "Boise City, ID" },
  { "key": "Bloomsburg_Berwick_PA", "text": "Bloomsburg-Berwick, PA" },
  { "key": "Boston_Cambridge_Newton_MA-NH", "text": "Boston-Cambridge-Newton, MA-NH" },
  { "key": "Bowling_Green_KY", "text": "Bowling Green, KY" },
  { "key": "Bremerton_Silverdale_WA", "text": "Bremerton-Silverdale, WA" },
  { "key": "Bridgeport_Stamford_Norwalk_CT", "text": "Bridgeport-Stamford-Norwalk, CT" },
  { "key": "Brownsville_Harlingen_TX", "text": "Brownsville-Harlingen, TX" },
  { "key": "Bismarck_ND", "text": "Bismarck, ND" },
  { "key": "Brunswick_GA", "text": "Brunswick, GA" },
  { "key": "Buffalo_Cheektowaga_Niagara_Falls_NY", "text": "Buffalo-Cheektowaga-Niagara Falls, NY" },
  { "key": "Burlington_NC", "text": "Burlington, NC" },
  { "key": "Burlington_South_Burlington_VT", "text": "Burlington-South Burlington, VT" },
  { "key": "Cape_Girardeau_MO-IL", "text": "Cape Girardeau, MO-IL" },
  { "key": "California_Lexington_Park_MD", "text": "California-Lexington Park, MD" },
  { "key": "Canton_Massillon_OH", "text": "Canton-Massillon, OH" },
  { "key": "Carson_City_NV", "text": "Carson City, NV" },
  { "key": "Casper_WY", "text": "Casper, WY" },
  { "key": "Chambersburg_Waynesboro_PA", "text": "Chambersburg-Waynesboro, PA" },
  { "key": "Cape_Coral_Fort_Myers_FL", "text": "Cape Coral-Fort Myers, FL" },
  { "key": "Cedar_Rapids_IA", "text": "Cedar Rapids, IA" },
  { "key": "Champaign_Urbana_IL", "text": "Champaign-Urbana, IL" },
  { "key": "Cheyenne_WY", "text": "Cheyenne, WY" },
  { "key": "Chicago_Naperville_Elgin_IL-IN-WI", "text": "Chicago-Naperville-Elgin, IL-IN-WI" },
  { "key": "Chico_CA", "text": "Chico, CA" },
  { "key": "Charlotte_Concord_Gastonia_NC-SC", "text": "Charlotte-Concord-Gastonia, NC-SC" },
  { "key": "Charleston_North_Charleston_SC", "text": "Charleston-North Charleston, SC" },
  { "key": "Chattanooga_TN-GA", "text": "Chattanooga, TN-GA" },
  { "key": "Charlottesville_VA", "text": "Charlottesville, VA" },
  { "key": "Charleston_WV", "text": "Charleston, WV" },
  { "key": "Cincinnati_OH-KY-IN", "text": "Cincinnati, OH-KY-IN" },
  { "key": "Clarksville_TN-KY", "text": "Clarksville, TN-KY" },
  { "key": "Cleveland_TN", "text": "Cleveland, TN" },
  { "key": "Cleveland_Elyria_OH", "text": "Cleveland-Elyria, OH" },
  { "key": "Coeur_d'Alene_ID", "text": "Coeur d'Alene, ID" },
  { "key": "Columbus_GA-AL", "text": "Columbus, GA-AL" },
  { "key": "Columbia_MO", "text": "Columbia, MO" },
  { "key": "Columbus_IN", "text": "Columbus, IN" },
  { "key": "Colorado_Springs_CO", "text": "Colorado Springs, CO" },
  { "key": "Corpus_Christi_TX", "text": "Corpus Christi, TX" },
  { "key": "Columbia_SC", "text": "Columbia, SC" },
  { "key": "Columbus_OH", "text": "Columbus, OH" },
  { "key": "Corvallis_OR", "text": "Corvallis, OR" },
  { "key": "Carbondale_Marion_IL", "text": "Carbondale-Marion, IL" },
  { "key": "Crestview_Fort_Walton_Beach_Destin_FL", "text": "Crestview-Fort Walton Beach-Destin, FL" },
  { "key": "College_Station_Bryan_TX", "text": "College Station-Bryan, TX" },
  { "key": "Cumberland_MD-WV", "text": "Cumberland, MD-WV" },
  { "key": "Dalton_GA", "text": "Dalton, GA" },
  { "key": "Danville_IL", "text": "Danville, IL" },
  { "key": "Dallas_Fort_Worth_Arlington_TX", "text": "Dallas-Fort Worth-Arlington, TX" },
  { "key": "Daphne_Fairhope_Foley_AL", "text": "Daphne-Fairhope-Foley, AL" },
  { "key": "Davenport_Moline_Rock_Island_IA-IL", "text": "Davenport-Moline-Rock Island, IA-IL" },
  { "key": "Dayton_OH", "text": "Dayton, OH" },
  { "key": "Decatur_IL", "text": "Decatur, IL" },
  { "key": "Deltona_Daytona_Beach_Ormond_Beach_FL", "text": "Deltona-Daytona Beach-Ormond Beach, FL" },
  { "key": "Denver_Aurora_Lakewood_CO", "text": "Denver-Aurora-Lakewood, CO" },
  { "key": "Des_Moines_West_Des_Moines_IA", "text": "Des Moines-West Des Moines, IA" },
  { "key": "Detroit_Warren_Dearborn_MI", "text": "Detroit-Warren-Dearborn, MI" },
  { "key": "Decatur_AL", "text": "Decatur, AL" },
  { "key": "Dothan_AL", "text": "Dothan, AL" },
  { "key": "Dover_DE", "text": "Dover, DE" },
  { "key": "Dubuque_IA", "text": "Dubuque, IA" },
  { "key": "Duluth_MN-WI", "text": "Duluth, MN-WI" },
  { "key": "Durham_Chapel_Hill_NC", "text": "Durham-Chapel Hill, NC" },
  { "key": "East_Stroudsburg_PA", "text": "East Stroudsburg, PA" },
  { "key": "Eau_Claire_WI", "text": "Eau Claire, WI" },
  { "key": "El_Centro_CA", "text": "El Centro, CA" },
  { "key": "Elizabethtown_Fort_Knox_KY", "text": "Elizabethtown-Fort Knox, KY" },
  { "key": "Elkhart_Goshen_IN", "text": "Elkhart-Goshen, IN" },
  { "key": "Elmira_NY", "text": "Elmira, NY" },
  { "key": "El_Paso_TX", "text": "El Paso, TX" },
  { "key": "Enid_OK", "text": "Enid, OK" },
  { "key": "Erie_PA", "text": "Erie, PA" },
  { "key": "Eugene_OR", "text": "Eugene, OR" },
  { "key": "Evansville_IN-KY", "text": "Evansville, IN-KY" },
  { "key": "Fayetteville_NC", "text": "Fayetteville, NC" },
  { "key": "Fairbanks_AK", "text": "Fairbanks, AK" },
  { "key": "Farmington_NM", "text": "Farmington, NM" },
  { "key": "Fargo_ND-MN", "text": "Fargo, ND-MN" },
  { "key": "Fayetteville_Springdale_Rogers_AR-MO", "text": "Fayetteville-Springdale-Rogers, AR-MO" },
  { "key": "Flagstaff_AZ", "text": "Flagstaff, AZ" },
  { "key": "Flint_MI", "text": "Flint, MI" },
  { "key": "Florence_SC", "text": "Florence, SC" },
  { "key": "Florence_Muscle_Shoals_AL", "text": "Florence-Muscle Shoals, AL" },
  { "key": "Fond_du_Lac_WI", "text": "Fond du Lac, WI" },
  { "key": "Fort_Collins_CO", "text": "Fort Collins, CO" },
  { "key": "Fort_Smith_AR-OK", "text": "Fort Smith, AR-OK" },
  { "key": "Fort_Wayne_IN", "text": "Fort Wayne, IN" },
  { "key": "Fresno_CA", "text": "Fresno, CA" },
  { "key": "Gadsden_AL", "text": "Gadsden, AL" },
  { "key": "Gainesville_GA", "text": "Gainesville, GA" },
  { "key": "Gainesville_FL", "text": "Gainesville, FL" },
  { "key": "Gettysburg_PA", "text": "Gettysburg, PA" },
  { "key": "Glens_Falls_NY", "text": "Glens Falls, NY" },
  { "key": "Goldsboro_NC", "text": "Goldsboro, NC" },
  { "key": "Grand_Rapids_Wyoming_MI", "text": "Grand Rapids-Wyoming, MI" },
  { "key": "Green_Bay_WI", "text": "Green Bay, WI" },
  { "key": "Grand_Island_NE", "text": "Grand Island, NE" },
  { "key": "Great_Falls_MT", "text": "Great Falls, MT" },
  { "key": "Grand_Forks_ND-MN", "text": "Grand Forks, ND-MN" },
  { "key": "Grand_Junction_CO", "text": "Grand Junction, CO" },
  { "key": "Greeley_CO", "text": "Greeley, CO" },
  { "key": "Greensboro_High_Point_NC", "text": "Greensboro-High Point, NC" },
  { "key": "Grants_Pass_OR", "text": "Grants Pass, OR" },
  { "key": "Greenville_Anderson_Mauldin_SC", "text": "Greenville-Anderson-Mauldin, SC" },
  { "key": "Gulfport_Biloxi_Pascagoula_MS", "text": "Gulfport-Biloxi-Pascagoula, MS" },
  { "key": "Greenville_NC", "text": "Greenville, NC" },
  { "key": "Hanford_Corcoran_CA", "text": "Hanford-Corcoran, CA" },
  { "key": "Harrisburg_Carlisle_PA", "text": "Harrisburg-Carlisle, PA" },
  { "key": "Harrisonburg_VA", "text": "Harrisonburg, VA" },
  { "key": "Hartford_West_Hartford_East_Hartford_CT", "text": "Hartford-West Hartford-East Hartford, CT" },
  { "key": "Hagerstown_Martinsburg_MD-WV", "text": "Hagerstown-Martinsburg, MD-WV" },
  { "key": "Hattiesburg_MS", "text": "Hattiesburg, MS" },
  { "key": "Hickory_Lenoir_Morganton_NC", "text": "Hickory-Lenoir-Morganton, NC" },
  { "key": "Hinesville_GA", "text": "Hinesville, GA" },
  { "key": "Hilton_Head_Island_Bluffton_Beaufort_SC", "text": "Hilton Head Island-Bluffton-Beaufort, SC" },
  { "key": "Hammond_LA", "text": "Hammond, LA" },
  { "key": "Houma_Thibodaux_LA", "text": "Houma-Thibodaux, LA" },
  { "key": "Homosassa_Springs_FL", "text": "Homosassa Springs, FL" },
  { "key": "Urban_Honolulu_HI", "text": "Urban Honolulu, HI" },
  { "key": "Hot_Springs_AR", "text": "Hot Springs, AR" },
  { "key": "Houston_The_Woodlands_Sugar_Land_TX", "text": "Houston-The Woodlands-Sugar Land, TX" },
  { "key": "Huntsville_AL", "text": "Huntsville, AL" },
  { "key": "Huntington_Ashland_WV-KY-OH", "text": "Huntington-Ashland, WV-KY-OH" },
  { "key": "Idaho_Falls_ID", "text": "Idaho Falls, ID" },
  { "key": "Indianapolis_Carmel_Anderson_IN", "text": "Indianapolis-Carmel-Anderson, IN" },
  { "key": "Iowa_City_IA", "text": "Iowa City, IA" },
  { "key": "Ithaca_NY", "text": "Ithaca, NY" },
  { "key": "Jacksonville_FL", "text": "Jacksonville, FL" },
  { "key": "Jackson_MI", "text": "Jackson, MI" },
  { "key": "Jackson_MS", "text": "Jackson, MS" },
  { "key": "Janesville_Beloit_WI", "text": "Janesville-Beloit, WI" },
  { "key": "Jacksonville_NC", "text": "Jacksonville, NC" },
  { "key": "Jackson_TN", "text": "Jackson, TN" },
  { "key": "Jefferson_City_MO", "text": "Jefferson City, MO" },
  { "key": "Jonesboro_AR", "text": "Jonesboro, AR" },
  { "key": "Johnstown_PA", "text": "Johnstown, PA" },
  { "key": "Johnson_City_TN", "text": "Johnson City, TN" },
  { "key": "Joplin_MO", "text": "Joplin, MO" },
  { "key": "Kahului_Wailuku_Lahaina_HI", "text": "Kahului-Wailuku-Lahaina, HI" },
  { "key": "Kankakee_IL", "text": "Kankakee, IL" },
  { "key": "Kalamazoo_Portage_MI", "text": "Kalamazoo-Portage, MI" },
  { "key": "Kansas_City_MO-KS", "text": "Kansas City, MO-KS" },
  { "key": "Killeen_Temple_TX", "text": "Killeen-Temple, TX" },
  { "key": "Kingsport_Bristol_Bristol_TN-VA", "text": "Kingsport-Bristol-Bristol, TN-VA" },
  { "key": "Kingston_NY", "text": "Kingston, NY" },
  { "key": "Kennewick_Richland_WA", "text": "Kennewick-Richland, WA" },
  { "key": "Knoxville_TN", "text": "Knoxville, TN" },
  { "key": "Kokomo_IN", "text": "Kokomo, IN" },
  { "key": "Lafayette_LA", "text": "Lafayette, LA" },
  { "key": "Lancaster_PA", "text": "Lancaster, PA" },
  { "key": "Laredo_TX", "text": "Laredo, TX" },
  { "key": "Lakeland_Winter_Haven_FL", "text": "Lakeland-Winter Haven, FL" },
  { "key": "Lafayette_West_Lafayette_IN", "text": "Lafayette-West Lafayette, IN" },
  { "key": "Lake_Havasu_City_Kingman_AZ", "text": "Lake Havasu City-Kingman, AZ" },
  { "key": "Lake_Charles_LA", "text": "Lake Charles, LA" },
  { "key": "Lansing_East_Lansing_MI", "text": "Lansing-East Lansing, MI" },
  { "key": "La_Crosse_Onalaska_WI-MN", "text": "La Crosse-Onalaska, WI-MN" },
  { "key": "Las_Vegas_Henderson_Paradise_NV", "text": "Las Vegas-Henderson-Paradise, NV" },
  { "key": "Lawton_OK", "text": "Lawton, OK" },
  { "key": "Lebanon_PA", "text": "Lebanon, PA" },
  { "key": "Lewiston_ID-WA", "text": "Lewiston, ID-WA" },
  { "key": "Lewiston_Auburn_ME", "text": "Lewiston-Auburn, ME" },
  { "key": "Lexington_Fayette_KY", "text": "Lexington-Fayette, KY" },
  { "key": "Lima_OH", "text": "Lima, OH" },
  { "key": "Lincoln_NE", "text": "Lincoln, NE" },
  { "key": "Little_Rock_North_Little_Rock_Conway_AR", "text": "Little Rock-North Little Rock-Conway, AR" },
  { "key": "Logan_UT-ID", "text": "Logan, UT-ID" },
  { "key": "Longview_TX", "text": "Longview, TX" },
  { "key": "Longview_WA", "text": "Longview, WA" },
  { "key": "Los_Angeles_Long_Beach_Anaheim_CA", "text": "Los Angeles-Long Beach-Anaheim, CA" },
  { "key": "Louisville/Jefferson_County_KY-IN", "text": "Louisville/Jefferson County, KY-IN" },
  { "key": "Las_Cruces_NM", "text": "Las Cruces, NM" },
  { "key": "Lubbock_TX", "text": "Lubbock, TX" },
  { "key": "Lawrence_KS", "text": "Lawrence, KS" },
  { "key": "Lynchburg_VA", "text": "Lynchburg, VA" },
  { "key": "Macon_Bibb_County_GA", "text": "Macon-Bibb County, GA" },
  { "key": "Madison_WI", "text": "Madison, WI" },
  { "key": "Mankato_North_Mankato_MN", "text": "Mankato-North Mankato, MN" },
  { "key": "Manhattan_KS", "text": "Manhattan, KS" },
  { "key": "Madera_CA", "text": "Madera, CA" },
  { "key": "Mansfield_OH", "text": "Mansfield, OH" },
  { "key": "McAllen_Edinburg_Mission_TX", "text": "McAllen-Edinburg-Mission, TX" },
  { "key": "Merced_CA", "text": "Merced, CA" },
  { "key": "Medford_OR", "text": "Medford, OR" },
  { "key": "Memphis_TN-MS-AR", "text": "Memphis, TN-MS-AR" },
  { "key": "Miami_Fort_Lauderdale_West_Palm_Beach_FL", "text": "Miami-Fort Lauderdale-West Palm Beach, FL" },
  { "key": "Michigan_City_La_Porte_IN", "text": "Michigan City-La Porte, IN" },
  { "key": "Midland_TX", "text": "Midland, TX" },
  { "key": "Milwaukee_Waukesha_West_Allis_WI", "text": "Milwaukee-Waukesha-West Allis, WI" },
  { "key": "Midland_MI", "text": "Midland, MI" },
  { "key": "Minneapolis_St._Paul_Bloomington_MN-WI", "text": "Minneapolis-St. Paul-Bloomington, MN-WI" },
  { "key": "Missoula_MT", "text": "Missoula, MT" },
  { "key": "Manchester_Nashua_NH", "text": "Manchester-Nashua, NH" },
  { "key": "Mobile_AL", "text": "Mobile, AL" },
  { "key": "Modesto_CA", "text": "Modesto, CA" },
  { "key": "Monroe_MI", "text": "Monroe, MI" },
  { "key": "Morgantown_WV", "text": "Morgantown, WV" },
  { "key": "Montgomery_AL", "text": "Montgomery, AL" },
  { "key": "Monroe_LA", "text": "Monroe, LA" },
  { "key": "Mount_Vernon_Anacortes_WA", "text": "Mount Vernon-Anacortes, WA" },
  { "key": "Morristown_TN", "text": "Morristown, TN" },
  { "key": "Muncie_IN", "text": "Muncie, IN" },
  { "key": "Muskegon_MI", "text": "Muskegon, MI" },
  { "key": "Myrtle_Beach_Conway_North_Myrtle_Beach_SC-NC", "text": "Myrtle Beach-Conway-North Myrtle Beach, SC-NC" },
  { "key": "Napa_CA", "text": "Napa, CA" },
  { "key": "Nashville_Davidson_Murfreesboro_Franklin_TN", "text": "Nashville-Davidson-Murfreesboro-Franklin, TN" },
  { "key": "Naples_Immokalee_Marco_Island_FL", "text": "Naples-Immokalee-Marco Island, FL" },
  { "key": "New_Bern_NC", "text": "New Bern, NC" },
  { "key": "New_Haven_Milford_CT", "text": "New Haven-Milford, CT" },
  { "key": "New_Orleans_Metairie_LA", "text": "New Orleans-Metairie, LA" },
  { "key": "New_York_Newark_Jersey_City_NY-NJ-PA", "text": "New York-Newark-Jersey City, NY-NJ-PA" },
  { "key": "Niles_Benton_Harbor_MI", "text": "Niles-Benton Harbor, MI" },
  { "key": "Norwich_New_London_CT", "text": "Norwich-New London, CT" },
  { "key": "North_Port_Sarasota_Bradenton_FL", "text": "North Port-Sarasota-Bradenton, FL" },
  { "key": "Ocala_FL", "text": "Ocala, FL" },
  { "key": "Ocean_City_NJ", "text": "Ocean City, NJ" },
  { "key": "Odessa_TX", "text": "Odessa, TX" },
  { "key": "Ogden_Clearfield_UT", "text": "Ogden-Clearfield, UT" },
  { "key": "Oklahoma_City_OK", "text": "Oklahoma City, OK" },
  { "key": "Olympia_Tumwater_WA", "text": "Olympia-Tumwater, WA" },
  { "key": "Omaha_Council_Bluffs_NE-IA", "text": "Omaha-Council Bluffs, NE-IA" },
  { "key": "Orlando_Kissimmee_Sanford_FL", "text": "Orlando-Kissimmee-Sanford, FL" },
  { "key": "Oshkosh_Neenah_WI", "text": "Oshkosh-Neenah, WI" },
  { "key": "Owensboro_KY", "text": "Owensboro, KY" },
  { "key": "Oxnard_Thousand_Oaks_Ventura_CA", "text": "Oxnard-Thousand Oaks-Ventura, CA" },
  { "key": "Palm_Bay_Melbourne_Titusville_FL", "text": "Palm Bay-Melbourne-Titusville, FL" },
  { "key": "Panama_City_FL", "text": "Panama City, FL" },
  { "key": "Parkersburg_Vienna_WV", "text": "Parkersburg-Vienna, WV" },
  { "key": "Pensacola_Ferry_Pass_Brent_FL", "text": "Pensacola-Ferry Pass-Brent, FL" },
  { "key": "Peoria_IL", "text": "Peoria, IL" },
  { "key": "Philadelphia_Camden_Wilmington_PA-NJ-DE-MD", "text": "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD" },
  { "key": "Phoenix_Mesa_Scottsdale_AZ", "text": "Phoenix-Mesa-Scottsdale, AZ" },
  { "key": "Pine_Bluff_AR", "text": "Pine Bluff, AR" },
  { "key": "Pittsfield_MA", "text": "Pittsfield, MA" },
  { "key": "Pittsburgh_PA", "text": "Pittsburgh, PA" },
  { "key": "Pocatello_ID", "text": "Pocatello, ID" },
  { "key": "Portland_South_Portland_ME", "text": "Portland-South Portland, ME" },
  { "key": "Portland_Vancouver_Hillsboro_OR-WA", "text": "Portland-Vancouver-Hillsboro, OR-WA" },
  { "key": "Prescott_AZ", "text": "Prescott, AZ" },
  { "key": "Providence_Warwick_RI-MA", "text": "Providence-Warwick, RI-MA" },
  { "key": "Provo_Orem_UT", "text": "Provo-Orem, UT" },
  { "key": "Port_St._Lucie_FL", "text": "Port St. Lucie, FL" },
  { "key": "Pueblo_CO", "text": "Pueblo, CO" },
  { "key": "Punta_Gorda_FL", "text": "Punta Gorda, FL" },
  { "key": "Racine_WI", "text": "Racine, WI" },
  { "key": "Raleigh_NC", "text": "Raleigh, NC" },
  { "key": "Rapid_City_SD", "text": "Rapid City, SD" },
  { "key": "Reading_PA", "text": "Reading, PA" },
  { "key": "Redding_CA", "text": "Redding, CA" },
  { "key": "Reno_NV", "text": "Reno, NV" },
  { "key": "Richmond_VA", "text": "Richmond, VA" },
  { "key": "Riverside_San_Bernardino_Ontario_CA", "text": "Riverside-San Bernardino-Ontario, CA" },
  { "key": "Roanoke_VA", "text": "Roanoke, VA" },
  { "key": "Rockford_IL", "text": "Rockford, IL" },
  { "key": "Rochester_MN", "text": "Rochester, MN" },
  { "key": "Rochester_NY", "text": "Rochester, NY" },
  { "key": "Rocky_Mount_NC", "text": "Rocky Mount, NC" },
  { "key": "Rome_GA", "text": "Rome, GA" },
  { "key": "Santa_Rosa_CA", "text": "Santa Rosa, CA" },
  { "key": "Sacramento_Roseville_Arden_Arcade_CA", "text": "Sacramento-Roseville-Arden-Arcade, CA" },
  { "key": "Salem_OR", "text": "Salem, OR" },
  { "key": "San_Francisco_Oakland_Hayward_CA", "text": "San Francisco-Oakland-Hayward, CA" },
  { "key": "Saginaw_MI", "text": "Saginaw, MI" },
  { "key": "San_Jose_Sunnyvale_Santa_Clara_CA", "text": "San Jose-Sunnyvale-Santa Clara, CA" },
  { "key": "Salinas_CA", "text": "Salinas, CA" },
  { "key": "San_Diego_Carlsbad_CA", "text": "San Diego-Carlsbad, CA" },
  { "key": "San_Angelo_TX", "text": "San Angelo, TX" },
  { "key": "Salisbury_MD-DE", "text": "Salisbury, MD-DE" },
  { "key": "Santa_Maria_Santa_Barbara_CA", "text": "Santa Maria-Santa Barbara, CA" },
  { "key": "St._George_UT", "text": "St. George, UT" },
  { "key": "Savannah_GA", "text": "Savannah, GA" },
  { "key": "Santa_Cruz_Watsonville_CA", "text": "Santa Cruz-Watsonville, CA" },
  { "key": "Salt_Lake_City_UT", "text": "Salt Lake City, UT" },
  { "key": "San_Antonio_New_Braunfels_TX", "text": "San Antonio-New Braunfels, TX" },
  { "key": "Seattle_Tacoma_Bellevue_WA", "text": "Seattle-Tacoma-Bellevue, WA" },
  { "key": "Sebring_FL", "text": "Sebring, FL" },
  { "key": "Santa_Fe_NM", "text": "Santa Fe, NM" },
  { "key": "Sheboygan_WI", "text": "Sheboygan, WI" },
  { "key": "Sherman_Denison_TX", "text": "Sherman-Denison, TX" },
  { "key": "Shreveport_Bossier_City_LA", "text": "Shreveport-Bossier City, LA" },
  { "key": "Sierra_Vista_Douglas_AZ", "text": "Sierra Vista-Douglas, AZ" },
  { "key": "Sioux_City_IA-NE-SD", "text": "Sioux City, IA-NE-SD" },
  { "key": "Sioux_Falls_SD", "text": "Sioux Falls, SD" },
  { "key": "San_Luis_Obispo_Paso_Robles_Arroyo_Grande_CA", "text": "San Luis Obispo-Paso Robles-Arroyo Grande, CA" },
  { "key": "South_Bend_Mishawaka_IN-MI", "text": "South Bend-Mishawaka, IN-MI" },
  { "key": "Spartanburg_SC", "text": "Spartanburg, SC" },
  { "key": "Springfield_OH", "text": "Springfield, OH" },
  { "key": "Springfield_MA", "text": "Springfield, MA" },
  { "key": "Springfield_MO", "text": "Springfield, MO" },
  { "key": "Spokane_Spokane_Valley_WA", "text": "Spokane-Spokane Valley, WA" },
  { "key": "Springfield_IL", "text": "Springfield, IL" },
  { "key": "St._Cloud_MN", "text": "St. Cloud, MN" },
  { "key": "State_College_PA", "text": "State College, PA" },
  { "key": "St._Joseph_MO-KS", "text": "St. Joseph, MO-KS" },
  { "key": "St._Louis_MO-IL", "text": "St. Louis, MO-IL" },
  { "key": "Stockton_Lodi_CA", "text": "Stockton-Lodi, CA" },
  { "key": "Staunton_Waynesboro_VA", "text": "Staunton-Waynesboro, VA" },
  { "key": "Sumter_SC", "text": "Sumter, SC" },
  { "key": "Scranton_Wilkes_Barre_Hazleton_PA", "text": "Scranton-Wilkes-Barre-Hazleton, PA" },
  { "key": "Syracuse_NY", "text": "Syracuse, NY" },
  { "key": "Tallahassee_FL", "text": "Tallahassee, FL" },
  { "key": "Tampa_St._Petersburg_Clearwater_FL", "text": "Tampa-St. Petersburg-Clearwater, FL" },
  { "key": "Terre_Haute_IN", "text": "Terre Haute, IN" },
  { "key": "Texarkana_TX-AR", "text": "Texarkana, TX-AR" },
  { "key": "The_Villages_FL", "text": "The Villages, FL" },
  { "key": "Toledo_OH", "text": "Toledo, OH" },
  { "key": "Topeka_KS", "text": "Topeka, KS" },
  { "key": "Trenton_NJ", "text": "Trenton, NJ" },
  { "key": "Tucson_AZ", "text": "Tucson, AZ" },
  { "key": "Tulsa_OK", "text": "Tulsa, OK" },
  { "key": "Tuscaloosa_AL", "text": "Tuscaloosa, AL" },
  { "key": "Twin_Falls_ID", "text": "Twin Falls, ID" },
  { "key": "Tyler_TX", "text": "Tyler, TX" },
  { "key": "Utica_Rome_NY", "text": "Utica-Rome, NY" },
  { "key": "Valdosta_GA", "text": "Valdosta, GA" },
  { "key": "Vallejo_Fairfield_CA", "text": "Vallejo-Fairfield, CA" },
  { "key": "Sebastian_Vero_Beach_FL", "text": "Sebastian-Vero Beach, FL" },
  { "key": "Victoria_TX", "text": "Victoria, TX" },
  { "key": "Vineland_Bridgeton_NJ", "text": "Vineland-Bridgeton, NJ" },
  { "key": "Virginia_Beach_Norfolk_Newport_News_VA-NC", "text": "Virginia Beach-Norfolk-Newport News, VA-NC" },
  { "key": "Visalia_Porterville_CA", "text": "Visalia-Porterville, CA" },
  { "key": "Waco_TX", "text": "Waco, TX" },
  { "key": "Watertown_Fort_Drum_NY", "text": "Watertown-Fort Drum, NY" },
  { "key": "Waterloo_Cedar_Falls_IA", "text": "Waterloo-Cedar Falls, IA" },
  { "key": "Walla_Walla_WA", "text": "Walla Walla, WA" },
  { "key": "Warner_Robins_GA", "text": "Warner Robins, GA" },
  { "key": "Washington_Arlington_Alexandria_DC-VA-MD-WV", "text": "Washington-Arlington-Alexandria, DC-VA-MD-WV" },
  { "key": "Wausau_WI", "text": "Wausau, WI" },
  { "key": "Weirton_Steubenville_WV-OH", "text": "Weirton-Steubenville, WV-OH" },
  { "key": "Wenatchee_WA", "text": "Wenatchee, WA" },
  { "key": "Wheeling_WV-OH", "text": "Wheeling, WV-OH" },
  { "key": "Wichita_KS", "text": "Wichita, KS" },
  { "key": "Wichita_Falls_TX", "text": "Wichita Falls, TX" },
  { "key": "Williamsport_PA", "text": "Williamsport, PA" },
  { "key": "Wilmington_NC", "text": "Wilmington, NC" },
  { "key": "Winchester_VA-WV", "text": "Winchester, VA-WV" },
  { "key": "Winston_Salem_NC", "text": "Winston-Salem, NC" },
  { "key": "Worcester_MA-CT", "text": "Worcester, MA-CT" },
  { "key": "Yakima_WA", "text": "Yakima, WA" },
  { "key": "York_Hanover_PA", "text": "York-Hanover, PA" },
  { "key": "Youngstown_Warren_Boardman_OH-PA", "text": "Youngstown-Warren-Boardman, OH-PA" },
  { "key": "Yuba_City_CA", "text": "Yuba City, CA" },
  { "key": "Yuma_AZ", "text": "Yuma, AZ" },
  ];