

export const locations = [
  {"key":"Albany, OR","text":"Albany, OR"},
{"key":"Abilene, TX","text":"Abilene, TX"},
{"key":"Akron, OH","text":"Akron, OH"},
{"key":"Albany-Schenectady-Troy, NY","text":"Albany-Schenectady-Troy, NY"},
{"key":"Albuquerque, NM","text":"Albuquerque, NM"},
{"key":"Alexandria, LA","text":"Alexandria, LA"},
{"key":"Allentown-Bethlehem-Easton, PA-NJ","text":"Allentown-Bethlehem-Easton, PA-NJ"},
{"key":"Albany, GA","text":"Albany, GA"},
{"key":"Altoona, PA","text":"Altoona, PA"},
{"key":"Amarillo, TX","text":"Amarillo, TX"},
{"key":"Ames, IA","text":"Ames, IA"},
{"key":"Anchorage, AK","text":"Anchorage, AK"},
{"key":"Anniston-Oxford-Jacksonville, AL","text":"Anniston-Oxford-Jacksonville, AL"},
{"key":"Ann Arbor, MI","text":"Ann Arbor, MI"},
{"key":"Appleton, WI","text":"Appleton, WI"},
{"key":"Asheville, NC","text":"Asheville, NC"},
{"key":"Atlantic City-Hammonton, NJ","text":"Atlantic City-Hammonton, NJ"},
{"key":"Athens-Clarke County, GA","text":"Athens-Clarke County, GA"},
{"key":"Atlanta-Sandy Springs-Roswell, GA","text":"Atlanta-Sandy Springs-Roswell, GA"},
{"key":"Auburn-Opelika, AL","text":"Auburn-Opelika, AL"},
{"key":"Augusta-Richmond County, GA-SC","text":"Augusta-Richmond County, GA-SC"},
{"key":"Austin-Round Rock, TX","text":"Austin-Round Rock, TX"},
{"key":"Bakersfield, CA","text":"Bakersfield, CA"},
{"key":"Baltimore-Columbia-Towson, MD","text":"Baltimore-Columbia-Towson, MD"},
{"key":"Bangor, ME","text":"Bangor, ME"},
{"key":"Barnstable Town, MA","text":"Barnstable Town, MA"},
{"key":"Baton Rouge, LA","text":"Baton Rouge, LA"},
{"key":"Battle Creek, MI","text":"Battle Creek, MI"},
{"key":"Bay City, MI","text":"Bay City, MI"},
{"key":"Beaumont-Port Arthur, TX","text":"Beaumont-Port Arthur, TX"},
{"key":"Beckley, WV","text":"Beckley, WV"},
{"key":"Bellingham, WA","text":"Bellingham, WA"},
{"key":"Billings, MT","text":"Billings, MT"},
{"key":"Binghamton, NY","text":"Binghamton, NY"},
{"key":"Birmingham-Hoover, AL","text":"Birmingham-Hoover, AL"},
{"key":"Blacksburg-Christiansburg-Radford, VA","text":"Blacksburg-Christiansburg-Radford, VA"},
{"key":"Boulder, CO","text":"Boulder, CO"},
{"key":"Bloomington, IN","text":"Bloomington, IN"},
{"key":"Bloomington, IL","text":"Bloomington, IL"},
{"key":"Bend-Redmond, OR","text":"Bend-Redmond, OR"},
{"key":"Boise City, ID","text":"Boise City, ID"},
{"key":"Bloomsburg-Berwick, PA","text":"Bloomsburg-Berwick, PA"},
{"key":"Boston-Cambridge-Newton, MA-NH","text":"Boston-Cambridge-Newton, MA-NH"},
{"key":"Bowling Green, KY","text":"Bowling Green, KY"},
{"key":"Bremerton-Silverdale, WA","text":"Bremerton-Silverdale, WA"},
{"key":"Bridgeport-Stamford-Norwalk, CT","text":"Bridgeport-Stamford-Norwalk, CT"},
{"key":"Brownsville-Harlingen, TX","text":"Brownsville-Harlingen, TX"},
{"key":"Bismarck, ND","text":"Bismarck, ND"},
{"key":"Brunswick, GA","text":"Brunswick, GA"},
{"key":"Buffalo-Cheektowaga-Niagara Falls, NY","text":"Buffalo-Cheektowaga-Niagara Falls, NY"},
{"key":"Burlington, NC","text":"Burlington, NC"},
{"key":"Burlington-South Burlington, VT","text":"Burlington-South Burlington, VT"},
{"key":"Cape Girardeau, MO-IL","text":"Cape Girardeau, MO-IL"},
{"key":"California-Lexington Park, MD","text":"California-Lexington Park, MD"},
{"key":"Canton-Massillon, OH","text":"Canton-Massillon, OH"},
{"key":"Carson City, NV","text":"Carson City, NV"},
{"key":"Casper, WY","text":"Casper, WY"},
{"key":"Chambersburg-Waynesboro, PA","text":"Chambersburg-Waynesboro, PA"},
{"key":"Cape Coral-Fort Myers, FL","text":"Cape Coral-Fort Myers, FL"},
{"key":"Cedar Rapids, IA","text":"Cedar Rapids, IA"},
{"key":"Champaign-Urbana, IL","text":"Champaign-Urbana, IL"},
{"key":"Cheyenne, WY","text":"Cheyenne, WY"},
{"key":"Chicago-Naperville-Elgin, IL-IN-WI","text":"Chicago-Naperville-Elgin, IL-IN-WI"},
{"key":"Chico, CA","text":"Chico, CA"},
{"key":"Charlotte-Concord-Gastonia, NC-SC","text":"Charlotte-Concord-Gastonia, NC-SC"},
{"key":"Charleston-North Charleston, SC","text":"Charleston-North Charleston, SC"},
{"key":"Chattanooga, TN-GA","text":"Chattanooga, TN-GA"},
{"key":"Charlottesville, VA","text":"Charlottesville, VA"},
{"key":"Charleston, WV","text":"Charleston, WV"},
{"key":"Cincinnati, OH-KY-IN","text":"Cincinnati, OH-KY-IN"},
{"key":"Clarksville, TN-KY","text":"Clarksville, TN-KY"},
{"key":"Cleveland, TN","text":"Cleveland, TN"},
{"key":"Cleveland-Elyria, OH","text":"Cleveland-Elyria, OH"},
{"key":"Coeur d'Alene, ID","text":"Coeur d'Alene, ID"},
{"key":"Columbus, GA-AL","text":"Columbus, GA-AL"},
{"key":"Columbia, MO","text":"Columbia, MO"},
{"key":"Columbus, IN","text":"Columbus, IN"},
{"key":"Colorado Springs, CO","text":"Colorado Springs, CO"},
{"key":"Corpus Christi, TX","text":"Corpus Christi, TX"},
{"key":"Columbia, SC","text":"Columbia, SC"},
{"key":"Columbus, OH","text":"Columbus, OH"},
{"key":"Corvallis, OR","text":"Corvallis, OR"},
{"key":"Carbondale-Marion, IL","text":"Carbondale-Marion, IL"},
{"key":"Crestview-Fort Walton Beach-Destin, FL","text":"Crestview-Fort Walton Beach-Destin, FL"},
{"key":"College Station-Bryan, TX","text":"College Station-Bryan, TX"},
{"key":"Cumberland, MD-WV","text":"Cumberland, MD-WV"},
{"key":"Dalton, GA","text":"Dalton, GA"},
{"key":"Danville, IL","text":"Danville, IL"},
{"key":"Dallas-Fort Worth-Arlington, TX","text":"Dallas-Fort Worth-Arlington, TX"},
{"key":"Daphne-Fairhope-Foley, AL","text":"Daphne-Fairhope-Foley, AL"},
{"key":"Davenport-Moline-Rock Island, IA-IL","text":"Davenport-Moline-Rock Island, IA-IL"},
{"key":"Dayton, OH","text":"Dayton, OH"},
{"key":"Decatur, IL","text":"Decatur, IL"},
{"key":"Deltona-Daytona Beach-Ormond Beach, FL","text":"Deltona-Daytona Beach-Ormond Beach, FL"},
{"key":"Denver-Aurora-Lakewood, CO","text":"Denver-Aurora-Lakewood, CO"},
{"key":"Des Moines-West Des Moines, IA","text":"Des Moines-West Des Moines, IA"},
{"key":"Detroit-Warren-Dearborn, MI","text":"Detroit-Warren-Dearborn, MI"},
{"key":"Decatur, AL","text":"Decatur, AL"},
{"key":"Dothan, AL","text":"Dothan, AL"},
{"key":"Dover, DE","text":"Dover, DE"},
{"key":"Dubuque, IA","text":"Dubuque, IA"},
{"key":"Duluth, MN-WI","text":"Duluth, MN-WI"},
{"key":"Durham-Chapel Hill, NC","text":"Durham-Chapel Hill, NC"},
{"key":"East Stroudsburg, PA","text":"East Stroudsburg, PA"},
{"key":"Eau Claire, WI","text":"Eau Claire, WI"},
{"key":"El Centro, CA","text":"El Centro, CA"},
{"key":"Elizabethtown-Fort Knox, KY","text":"Elizabethtown-Fort Knox, KY"},
{"key":"Elkhart-Goshen, IN","text":"Elkhart-Goshen, IN"},
{"key":"Elmira, NY","text":"Elmira, NY"},
{"key":"El Paso, TX","text":"El Paso, TX"},
{"key":"Enid, OK","text":"Enid, OK"},
{"key":"Erie, PA","text":"Erie, PA"},
{"key":"Eugene, OR","text":"Eugene, OR"},
{"key":"Evansville, IN-KY","text":"Evansville, IN-KY"},
{"key":"Fayetteville, NC","text":"Fayetteville, NC"},
{"key":"Fairbanks, AK","text":"Fairbanks, AK"},
{"key":"Farmington, NM","text":"Farmington, NM"},
{"key":"Fargo, ND-MN","text":"Fargo, ND-MN"},
{"key":"Fayetteville-Springdale-Rogers, AR-MO","text":"Fayetteville-Springdale-Rogers, AR-MO"},
{"key":"Flagstaff, AZ","text":"Flagstaff, AZ"},
{"key":"Flint, MI","text":"Flint, MI"},
{"key":"Florence, SC","text":"Florence, SC"},
{"key":"Florence-Muscle Shoals, AL","text":"Florence-Muscle Shoals, AL"},
{"key":"Fond du Lac, WI","text":"Fond du Lac, WI"},
{"key":"Fort Collins, CO","text":"Fort Collins, CO"},
{"key":"Fort Smith, AR-OK","text":"Fort Smith, AR-OK"},
{"key":"Fort Wayne, IN","text":"Fort Wayne, IN"},
{"key":"Fresno, CA","text":"Fresno, CA"},
{"key":"Gadsden, AL","text":"Gadsden, AL"},
{"key":"Gainesville, GA","text":"Gainesville, GA"},
{"key":"Gainesville, FL","text":"Gainesville, FL"},
{"key":"Gettysburg, PA","text":"Gettysburg, PA"},
{"key":"Glens Falls, NY","text":"Glens Falls, NY"},
{"key":"Goldsboro, NC","text":"Goldsboro, NC"},
{"key":"Grand Rapids-Wyoming, MI","text":"Grand Rapids-Wyoming, MI"},
{"key":"Green Bay, WI","text":"Green Bay, WI"},
{"key":"Grand Island, NE","text":"Grand Island, NE"},
{"key":"Great Falls, MT","text":"Great Falls, MT"},
{"key":"Grand Forks, ND-MN","text":"Grand Forks, ND-MN"},
{"key":"Grand Junction, CO","text":"Grand Junction, CO"},
{"key":"Greeley, CO","text":"Greeley, CO"},
{"key":"Greensboro-High Point, NC","text":"Greensboro-High Point, NC"},
{"key":"Grants Pass, OR","text":"Grants Pass, OR"},
{"key":"Greenville-Anderson-Mauldin, SC","text":"Greenville-Anderson-Mauldin, SC"},
{"key":"Gulfport-Biloxi-Pascagoula, MS","text":"Gulfport-Biloxi-Pascagoula, MS"},
{"key":"Greenville, NC","text":"Greenville, NC"},
{"key":"Hanford-Corcoran, CA","text":"Hanford-Corcoran, CA"},
{"key":"Harrisburg-Carlisle, PA","text":"Harrisburg-Carlisle, PA"},
{"key":"Harrisonburg, VA","text":"Harrisonburg, VA"},
{"key":"Hartford-West Hartford-East Hartford, CT","text":"Hartford-West Hartford-East Hartford, CT"},
{"key":"Hagerstown-Martinsburg, MD-WV","text":"Hagerstown-Martinsburg, MD-WV"},
{"key":"Hattiesburg, MS","text":"Hattiesburg, MS"},
{"key":"Hickory-Lenoir-Morganton, NC","text":"Hickory-Lenoir-Morganton, NC"},
{"key":"Hinesville, GA","text":"Hinesville, GA"},
{"key":"Hilton Head Island-Bluffton-Beaufort, SC","text":"Hilton Head Island-Bluffton-Beaufort, SC"},
{"key":"Hammond, LA","text":"Hammond, LA"},
{"key":"Houma-Thibodaux, LA","text":"Houma-Thibodaux, LA"},
{"key":"Homosassa Springs, FL","text":"Homosassa Springs, FL"},
{"key":"Urban Honolulu, HI","text":"Urban Honolulu, HI"},
{"key":"Hot Springs, AR","text":"Hot Springs, AR"},
{"key":"Houston-The Woodlands-Sugar Land, TX","text":"Houston-The Woodlands-Sugar Land, TX"},
{"key":"Huntsville, AL","text":"Huntsville, AL"},
{"key":"Huntington-Ashland, WV-KY-OH","text":"Huntington-Ashland, WV-KY-OH"},
{"key":"Idaho Falls, ID","text":"Idaho Falls, ID"},
{"key":"Indianapolis-Carmel-Anderson, IN","text":"Indianapolis-Carmel-Anderson, IN"},
{"key":"Iowa City, IA","text":"Iowa City, IA"},
{"key":"Ithaca, NY","text":"Ithaca, NY"},
{"key":"Jacksonville, FL","text":"Jacksonville, FL"},
{"key":"Jackson, MI","text":"Jackson, MI"},
{"key":"Jackson, MS","text":"Jackson, MS"},
{"key":"Janesville-Beloit, WI","text":"Janesville-Beloit, WI"},
{"key":"Jacksonville, NC","text":"Jacksonville, NC"},
{"key":"Jackson, TN","text":"Jackson, TN"},
{"key":"Jefferson City, MO","text":"Jefferson City, MO"},
{"key":"Jonesboro, AR","text":"Jonesboro, AR"},
{"key":"Johnstown, PA","text":"Johnstown, PA"},
{"key":"Johnson City, TN","text":"Johnson City, TN"},
{"key":"Joplin, MO","text":"Joplin, MO"},
{"key":"Kahului-Wailuku-Lahaina, HI","text":"Kahului-Wailuku-Lahaina, HI"},
{"key":"Kankakee, IL","text":"Kankakee, IL"},
{"key":"Kalamazoo-Portage, MI","text":"Kalamazoo-Portage, MI"},
{"key":"Kansas City, MO-KS","text":"Kansas City, MO-KS"},
{"key":"Killeen-Temple, TX","text":"Killeen-Temple, TX"},
{"key":"Kingsport-Bristol-Bristol, TN-VA","text":"Kingsport-Bristol-Bristol, TN-VA"},
{"key":"Kingston, NY","text":"Kingston, NY"},
{"key":"Kennewick-Richland, WA","text":"Kennewick-Richland, WA"},
{"key":"Knoxville, TN","text":"Knoxville, TN"},
{"key":"Kokomo, IN","text":"Kokomo, IN"},
{"key":"Lafayette, LA","text":"Lafayette, LA"},
{"key":"Lancaster, PA","text":"Lancaster, PA"},
{"key":"Laredo, TX","text":"Laredo, TX"},
{"key":"Lakeland-Winter Haven, FL","text":"Lakeland-Winter Haven, FL"},
{"key":"Lafayette-West Lafayette, IN","text":"Lafayette-West Lafayette, IN"},
{"key":"Lake Havasu City-Kingman, AZ","text":"Lake Havasu City-Kingman, AZ"},
{"key":"Lake Charles, LA","text":"Lake Charles, LA"},
{"key":"Lansing-East Lansing, MI","text":"Lansing-East Lansing, MI"},
{"key":"La Crosse-Onalaska, WI-MN","text":"La Crosse-Onalaska, WI-MN"},
{"key":"Las Vegas-Henderson-Paradise, NV","text":"Las Vegas-Henderson-Paradise, NV"},
{"key":"Lawton, OK","text":"Lawton, OK"},
{"key":"Lebanon, PA","text":"Lebanon, PA"},
{"key":"Lewiston, ID-WA","text":"Lewiston, ID-WA"},
{"key":"Lewiston-Auburn, ME","text":"Lewiston-Auburn, ME"},
{"key":"Lexington-Fayette, KY","text":"Lexington-Fayette, KY"},
{"key":"Lima, OH","text":"Lima, OH"},
{"key":"Lincoln, NE","text":"Lincoln, NE"},
{"key":"Little Rock-North Little Rock-Conway, AR","text":"Little Rock-North Little Rock-Conway, AR"},
{"key":"Logan, UT-ID","text":"Logan, UT-ID"},
{"key":"Longview, TX","text":"Longview, TX"},
{"key":"Longview, WA","text":"Longview, WA"},
{"key":"Los Angeles-Long Beach-Anaheim, CA","text":"Los Angeles-Long Beach-Anaheim, CA"},
{"key":"Louisville/Jefferson County, KY-IN","text":"Louisville/Jefferson County, KY-IN"},
{"key":"Las Cruces, NM","text":"Las Cruces, NM"},
{"key":"Lubbock, TX","text":"Lubbock, TX"},
{"key":"Lawrence, KS","text":"Lawrence, KS"},
{"key":"Lynchburg, VA","text":"Lynchburg, VA"},
{"key":"Macon-Bibb County, GA","text":"Macon-Bibb County, GA"},
{"key":"Madison, WI","text":"Madison, WI"},
{"key":"Mankato-North Mankato, MN","text":"Mankato-North Mankato, MN"},
{"key":"Manhattan, KS","text":"Manhattan, KS"},
{"key":"Madera, CA","text":"Madera, CA"},
{"key":"Mansfield, OH","text":"Mansfield, OH"},
{"key":"McAllen-Edinburg-Mission, TX","text":"McAllen-Edinburg-Mission, TX"},
{"key":"Merced, CA","text":"Merced, CA"},
{"key":"Medford, OR","text":"Medford, OR"},
{"key":"Memphis, TN-MS-AR","text":"Memphis, TN-MS-AR"},
{"key":"Miami-Fort Lauderdale-West Palm Beach, FL","text":"Miami-Fort Lauderdale-West Palm Beach, FL"},
{"key":"Michigan City-La Porte, IN","text":"Michigan City-La Porte, IN"},
{"key":"Midland, TX","text":"Midland, TX"},
{"key":"Milwaukee-Waukesha-West Allis, WI","text":"Milwaukee-Waukesha-West Allis, WI"},
{"key":"Midland, MI","text":"Midland, MI"},
{"key":"Minneapolis-St. Paul-Bloomington, MN-WI","text":"Minneapolis-St. Paul-Bloomington, MN-WI"},
{"key":"Missoula, MT","text":"Missoula, MT"},
{"key":"Manchester-Nashua, NH","text":"Manchester-Nashua, NH"},
{"key":"Mobile, AL","text":"Mobile, AL"},
{"key":"Modesto, CA","text":"Modesto, CA"},
{"key":"Monroe, MI","text":"Monroe, MI"},
{"key":"Morgantown, WV","text":"Morgantown, WV"},
{"key":"Montgomery, AL","text":"Montgomery, AL"},
{"key":"Monroe, LA","text":"Monroe, LA"},
{"key":"Mount Vernon-Anacortes, WA","text":"Mount Vernon-Anacortes, WA"},
{"key":"Morristown, TN","text":"Morristown, TN"},
{"key":"Muncie, IN","text":"Muncie, IN"},
{"key":"Muskegon, MI","text":"Muskegon, MI"},
{"key":"Myrtle Beach-Conway-North Myrtle Beach, SC-NC","text":"Myrtle Beach-Conway-North Myrtle Beach, SC-NC"},
{"key":"Napa, CA","text":"Napa, CA"},
{"key":"Nashville-Davidson-Murfreesboro-Franklin, TN","text":"Nashville-Davidson-Murfreesboro-Franklin, TN"},
{"key":"Naples-Immokalee-Marco Island, FL","text":"Naples-Immokalee-Marco Island, FL"},
{"key":"New Bern, NC","text":"New Bern, NC"},
{"key":"New Haven-Milford, CT","text":"New Haven-Milford, CT"},
{"key":"New Orleans-Metairie, LA","text":"New Orleans-Metairie, LA"},
{"key":"New York-Newark-Jersey City, NY-NJ-PA","text":"New York-Newark-Jersey City, NY-NJ-PA"},
{"key":"Niles-Benton Harbor, MI","text":"Niles-Benton Harbor, MI"},
{"key":"Norwich-New London, CT","text":"Norwich-New London, CT"},
{"key":"North Port-Sarasota-Bradenton, FL","text":"North Port-Sarasota-Bradenton, FL"},
{"key":"Ocala, FL","text":"Ocala, FL"},
{"key":"Ocean City, NJ","text":"Ocean City, NJ"},
{"key":"Odessa, TX","text":"Odessa, TX"},
{"key":"Ogden-Clearfield, UT","text":"Ogden-Clearfield, UT"},
{"key":"Oklahoma City, OK","text":"Oklahoma City, OK"},
{"key":"Olympia-Tumwater, WA","text":"Olympia-Tumwater, WA"},
{"key":"Omaha-Council Bluffs, NE-IA","text":"Omaha-Council Bluffs, NE-IA"},
{"key":"Orlando-Kissimmee-Sanford, FL","text":"Orlando-Kissimmee-Sanford, FL"},
{"key":"Oshkosh-Neenah, WI","text":"Oshkosh-Neenah, WI"},
{"key":"Owensboro, KY","text":"Owensboro, KY"},
{"key":"Oxnard-Thousand Oaks-Ventura, CA","text":"Oxnard-Thousand Oaks-Ventura, CA"},
{"key":"Palm Bay-Melbourne-Titusville, FL","text":"Palm Bay-Melbourne-Titusville, FL"},
{"key":"Panama City, FL","text":"Panama City, FL"},
{"key":"Parkersburg-Vienna, WV","text":"Parkersburg-Vienna, WV"},
{"key":"Pensacola-Ferry Pass-Brent, FL","text":"Pensacola-Ferry Pass-Brent, FL"},
{"key":"Peoria, IL","text":"Peoria, IL"},
{"key":"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD","text":"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD"},
{"key":"Phoenix-Mesa-Scottsdale, AZ","text":"Phoenix-Mesa-Scottsdale, AZ"},
{"key":"Pine Bluff, AR","text":"Pine Bluff, AR"},
{"key":"Pittsfield, MA","text":"Pittsfield, MA"},
{"key":"Pittsburgh, PA","text":"Pittsburgh, PA"},
{"key":"Pocatello, ID","text":"Pocatello, ID"},
{"key":"Portland-South Portland, ME","text":"Portland-South Portland, ME"},
{"key":"Portland-Vancouver-Hillsboro, OR-WA","text":"Portland-Vancouver-Hillsboro, OR-WA"},
{"key":"Prescott, AZ","text":"Prescott, AZ"},
{"key":"Providence-Warwick, RI-MA","text":"Providence-Warwick, RI-MA"},
{"key":"Provo-Orem, UT","text":"Provo-Orem, UT"},
{"key":"Port St. Lucie, FL","text":"Port St. Lucie, FL"},
{"key":"Pueblo, CO","text":"Pueblo, CO"},
{"key":"Punta Gorda, FL","text":"Punta Gorda, FL"},
{"key":"Racine, WI","text":"Racine, WI"},
{"key":"Raleigh, NC","text":"Raleigh, NC"},
{"key":"Rapid City, SD","text":"Rapid City, SD"},
{"key":"Reading, PA","text":"Reading, PA"},
{"key":"Redding, CA","text":"Redding, CA"},
{"key":"Reno, NV","text":"Reno, NV"},
{"key":"Richmond, VA","text":"Richmond, VA"},
{"key":"Riverside-San Bernardino-Ontario, CA","text":"Riverside-San Bernardino-Ontario, CA"},
{"key":"Roanoke, VA","text":"Roanoke, VA"},
{"key":"Rockford, IL","text":"Rockford, IL"},
{"key":"Rochester, MN","text":"Rochester, MN"},
{"key":"Rochester, NY","text":"Rochester, NY"},
{"key":"Rocky Mount, NC","text":"Rocky Mount, NC"},
{"key":"Rome, GA","text":"Rome, GA"},
{"key":"Santa Rosa, CA","text":"Santa Rosa, CA"},
{"key":"Sacramento-Roseville-Arden-Arcade, CA","text":"Sacramento-Roseville-Arden-Arcade, CA"},
{"key":"Salem, OR","text":"Salem, OR"},
{"key":"San Francisco-Oakland-Hayward, CA","text":"San Francisco-Oakland-Hayward, CA"},
{"key":"Saginaw, MI","text":"Saginaw, MI"},
{"key":"San Jose-Sunnyvale-Santa Clara, CA","text":"San Jose-Sunnyvale-Santa Clara, CA"},
{"key":"Salinas, CA","text":"Salinas, CA"},
{"key":"San Diego-Carlsbad, CA","text":"San Diego-Carlsbad, CA"},
{"key":"San Angelo, TX","text":"San Angelo, TX"},
{"key":"Salisbury, MD-DE","text":"Salisbury, MD-DE"},
{"key":"Santa Maria-Santa Barbara, CA","text":"Santa Maria-Santa Barbara, CA"},
{"key":"St. George, UT","text":"St. George, UT"},
{"key":"Savannah, GA","text":"Savannah, GA"},
{"key":"Santa Cruz-Watsonville, CA","text":"Santa Cruz-Watsonville, CA"},
{"key":"Salt Lake City, UT","text":"Salt Lake City, UT"},
{"key":"San Antonio-New Braunfels, TX","text":"San Antonio-New Braunfels, TX"},
{"key":"Seattle-Tacoma-Bellevue, WA","text":"Seattle-Tacoma-Bellevue, WA"},
{"key":"Sebring, FL","text":"Sebring, FL"},
{"key":"Santa Fe, NM","text":"Santa Fe, NM"},
{"key":"Sheboygan, WI","text":"Sheboygan, WI"},
{"key":"Sherman-Denison, TX","text":"Sherman-Denison, TX"},
{"key":"Shreveport-Bossier City, LA","text":"Shreveport-Bossier City, LA"},
{"key":"Sierra Vista-Douglas, AZ","text":"Sierra Vista-Douglas, AZ"},
{"key":"Sioux City, IA-NE-SD","text":"Sioux City, IA-NE-SD"},
{"key":"Sioux Falls, SD","text":"Sioux Falls, SD"},
{"key":"San Luis Obispo-Paso Robles-Arroyo Grande, CA","text":"San Luis Obispo-Paso Robles-Arroyo Grande, CA"},
{"key":"South Bend-Mishawaka, IN-MI","text":"South Bend-Mishawaka, IN-MI"},
{"key":"Spartanburg, SC","text":"Spartanburg, SC"},
{"key":"Springfield, OH","text":"Springfield, OH"},
{"key":"Springfield, MA","text":"Springfield, MA"},
{"key":"Springfield, MO","text":"Springfield, MO"},
{"key":"Spokane-Spokane Valley, WA","text":"Spokane-Spokane Valley, WA"},
{"key":"Springfield, IL","text":"Springfield, IL"},
{"key":"St. Cloud, MN","text":"St. Cloud, MN"},
{"key":"State College, PA","text":"State College, PA"},
{"key":"St. Joseph, MO-KS","text":"St. Joseph, MO-KS"},
{"key":"St. Louis, MO-IL","text":"St. Louis, MO-IL"},
{"key":"Stockton-Lodi, CA","text":"Stockton-Lodi, CA"},
{"key":"Staunton-Waynesboro, VA","text":"Staunton-Waynesboro, VA"},
{"key":"Sumter, SC","text":"Sumter, SC"},
{"key":"Scranton-Wilkes-Barre-Hazleton, PA","text":"Scranton-Wilkes-Barre-Hazleton, PA"},
{"key":"Syracuse, NY","text":"Syracuse, NY"},
{"key":"Tallahassee, FL","text":"Tallahassee, FL"},
{"key":"Tampa-St. Petersburg-Clearwater, FL","text":"Tampa-St. Petersburg-Clearwater, FL"},
{"key":"Terre Haute, IN","text":"Terre Haute, IN"},
{"key":"Texarkana, TX-AR","text":"Texarkana, TX-AR"},
{"key":"The Villages, FL","text":"The Villages, FL"},
{"key":"Toledo, OH","text":"Toledo, OH"},
{"key":"Topeka, KS","text":"Topeka, KS"},
{"key":"Trenton, NJ","text":"Trenton, NJ"},
{"key":"Tucson, AZ","text":"Tucson, AZ"},
{"key":"Tulsa, OK","text":"Tulsa, OK"},
{"key":"Tuscaloosa, AL","text":"Tuscaloosa, AL"},
{"key":"Twin Falls, ID","text":"Twin Falls, ID"},
{"key":"Tyler, TX","text":"Tyler, TX"},
{"key":"Utica-Rome, NY","text":"Utica-Rome, NY"},
{"key":"Valdosta, GA","text":"Valdosta, GA"},
{"key":"Vallejo-Fairfield, CA","text":"Vallejo-Fairfield, CA"},
{"key":"Sebastian-Vero Beach, FL","text":"Sebastian-Vero Beach, FL"},
{"key":"Victoria, TX","text":"Victoria, TX"},
{"key":"Vineland-Bridgeton, NJ","text":"Vineland-Bridgeton, NJ"},
{"key":"Virginia Beach-Norfolk-Newport News, VA-NC","text":"Virginia Beach-Norfolk-Newport News, VA-NC"},
{"key":"Visalia-Porterville, CA","text":"Visalia-Porterville, CA"},
{"key":"Waco, TX","text":"Waco, TX"},
{"key":"Watertown-Fort Drum, NY","text":"Watertown-Fort Drum, NY"},
{"key":"Waterloo-Cedar Falls, IA","text":"Waterloo-Cedar Falls, IA"},
{"key":"Walla Walla, WA","text":"Walla Walla, WA"},
{"key":"Warner Robins, GA","text":"Warner Robins, GA"},
{"key":"Washington-Arlington-Alexandria, DC-VA-MD-WV","text":"Washington-Arlington-Alexandria, DC-VA-MD-WV"},
{"key":"Wausau, WI","text":"Wausau, WI"},
{"key":"Weirton-Steubenville, WV-OH","text":"Weirton-Steubenville, WV-OH"},
{"key":"Wenatchee, WA","text":"Wenatchee, WA"},
{"key":"Wheeling, WV-OH","text":"Wheeling, WV-OH"},
{"key":"Wichita, KS","text":"Wichita, KS"},
{"key":"Wichita Falls, TX","text":"Wichita Falls, TX"},
{"key":"Williamsport, PA","text":"Williamsport, PA"},
{"key":"Wilmington, NC","text":"Wilmington, NC"},
{"key":"Winchester, VA-WV","text":"Winchester, VA-WV"},
{"key":"Winston-Salem, NC","text":"Winston-Salem, NC"},
{"key":"Worcester, MA-CT","text":"Worcester, MA-CT"},
{"key":"Yakima, WA","text":"Yakima, WA"},
{"key":"York-Hanover, PA","text":"York-Hanover, PA"},
{"key":"Youngstown-Warren-Boardman, OH-PA","text":"Youngstown-Warren-Boardman, OH-PA"},
{"key":"Yuba City, CA","text":"Yuba City, CA"},
{"key":"Yuma, AZ","text":"Yuma, AZ"},
  ];